export const countries: string[] = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Republic)",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
]

export const pricingMatrix: Record<string, Record<number, number>> = {
  A: { 1: 60, 2: 50, 3: 0, 4: 50 },
  B: { 1: 150, 2: 100, 3: 0, 4: 100 },
}

export const professionSubgroups: Record<number, string[]> = {
  1: [
    "General Practitioner / Family Medicine", "Cardiologist", "Pediatrician", "Surgeon",
    "Gynecologist / Obstetrician", "Registered Nurse", "Dentist", "Psychologist", "Other...",
  ],
  2: [
    "Internal Medicine Resident", "General Surgery Resident",
    "Pediatrics Resident", "Gynecology Resident", "Family Medicine Specialization", "Other...",
  ],
  3: [
    "Medical Student", "Nursing Student", "Dentistry Student",
    "Psychology Student", "Other...",
  ],
  4: [
    "Healthcare Administration", "Social Work / Chaplain",
    "Scientific Researcher", "Medical Technology", "Other...",
  ],
}

export const memberTypeLabels: Record<number, { label: string; desc: string }> = {
  1: { label: "Licensed Health Professional", desc: "Physicians, nurses, specialists with an active license." },
  2: { label: "Resident / Post graduate", desc: "Graduates completing residency or specialization programs." },
  3: { label: "Student", desc: "Access the latest articles and join our newsletter — completely free." },
  4: { label: "Non-Medical Professional", desc: "Support the health mission from other professional fields." },
}

export const paymentOptions = [
  { value: 1, label: "Annual", desc: "One payment per year" },
  { value: 2, label: "2 installments", desc: "Every 6 months" },
  { value: 3, label: "3 installments", desc: "Every 4 months" },
]

// Live mode prices (2026-08)
export const PRICE_IDS: Record<number, Record<string, Record<number, string>>> = {
  1: {
    A: { 1: "price_1U2YE33HQOpcbsNlNYb30VGy", 2: "price_1U2YE33HQOpcbsNls2Swc7Tk", 3: "price_1U2YE33HQOpcbsNlYK0QlEeb" },
    B: { 1: "price_1U2YE23HQOpcbsNlQHpyh4ej", 2: "price_1U2YE23HQOpcbsNlHxSReaDp", 3: "price_1U2YE13HQOpcbsNlLW3WbPik" },
  },
  2: {
    A: { 1: "price_1U2YE33HQOpcbsNlhR9qhVW3", 2: "price_1U2YE23HQOpcbsNlHrHBgQ5v", 3: "price_1U2YE33HQOpcbsNlqZytAmTI" },
    B: { 1: "price_1U2YE23HQOpcbsNlo7FiZUIK", 2: "price_1U2YE13HQOpcbsNli1FBeuoz", 3: "price_1U2YE13HQOpcbsNlNUeGjbUM" },
  },
  4: {
    A: { 1: "price_1U2YE33HQOpcbsNl7d2azGNv", 2: "price_1U2YE33HQOpcbsNlxyYHHuQe", 3: "price_1U2YE23HQOpcbsNlJRLR46qI" },
    B: { 1: "price_1U2YE23HQOpcbsNl2EZNRUIt", 2: "price_1U2YE13HQOpcbsNlIBDasmIL", 3: "price_1U2YE13HQOpcbsNlSROVZhKq" },
  },
}
